# Generated by Django 5.0.7 on 2024-10-18 14:17

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=encrypted_model_fields.fields.EncryptedIntegerField(),
        ),
    ]
